[package]
name = "quizify-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.6"
dotenv = "0.15"
env_logger = "0.10"

[[bin]]  # Explicitly define the binary target
name = "quizify-backend"
path = "src/main.rs"
